server:
  port: 9001
  servlet:
    context-path: /gconfigserver

spring:
  main:
    banner-mode: off
  application:
    name: gm-config-service
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: https://github.com/sachin125/gavayam-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka

logging:
  file:
    name: /home/uulin/gavayam/${spring.application.name}.log
    path: /home/uulin/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %log{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %log{36} - %msg%n"
  level:
    root: info
    org:
      springframework:
        web: debug
        security: debug
        jpa: debug
        data: debug
        oauth2: debug
      hibernate:
        SQL: off
    com:
      gavayam: debug
  logback:
    rollingpolicy:
      file-name-pattern: /home/uulin/gavayam/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      max-file-size: 5MB
      total-size-cap: 50MB
      max-history: 10

